[versions]
plugin-android = "7.4.2"
plugin-kotlin = "1.8.10"
plugin-compose-multiplatform = "1.3.1"
plugin-gver = "0.46.0"

androidx-compose-ui = "1.3.3"
kotlinx-serialization = "1.5.0"
kotlinx-coroutines = "1.6.4"
kotlinx-datetime = "0.4.0"
image-loader = "1.2.10"
libres = "1.1.5"
ktor = "2.2.4"
napier = "2.6.1"
multiplatform-settings = "1.0.0"
voyager = "1.0.0-rc07"
koin = "3.3.3"
accompanist = "0.28.0"
coil = "2.2.2"
activity-compose = "1.6.1"
work-runtime-ktx = "2.8.0"
desugar-jdk-libs = "2.0.2"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "plugin-kotlin" }
plugin-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "plugin-kotlin" }
plugin-compose-multiplatform = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "plugin-compose-multiplatform" }
plugin-libres = { module = "io.github.skeptick.libres:gradle-plugin", version.ref = "libres" }
plugin-gver = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "plugin-gver" }

androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
compose-libres = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libres" }
compose-image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
voyager-navigator = { module = "ca.gosyer:voyager-navigator", version.ref = "voyager" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }

[bundles]
plugins = ["plugin-android", "plugin-kotlin",  "plugin-kotlin-serialization", "plugin-compose-multiplatform", "plugin-libres", "plugin-gver"]
